### ISSUE TITLE
"Error: Cannot find module '/Users/pdehaan/dev/tmp/del/next-app-test/bar/.next/build-stats.json'" when using Node 8 and npm 5

### ISSUE THREAD

**Issue by pdehaan** [segmentio/create-next-app#20]
### Description

"Error: Cannot find module '/Users/pdehaan/dev/tmp/del/next-app-test/bar/bar/.next/build-stats.json'" when using Node 8 and npm 5

### Expected behavior

Running `npm start` from the CLI should totally work.

### Actual behavior

Running `npm start` fails hard with the following output:

```sh
> npm start

> create-next-example-app@ start /Users/pdehaan/dev/tmp/del/next-app-test/bar
> next start

module.js:487
    throw err;
    ^

Error: Cannot find module '/Users/pdehaan/dev/tmp/del/next-app-test/bar/.next/build-stats.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new Server (/Users/pdehaan/dev/tmp/del/next-app-test/bar/bar/node_modules/next/dist/server/index.js:102:30)
    at Object.<anonymous> (/Users/pdehaan/dev/tmp/del/next-app-test/bar/bar/node_modules/next/dist/bin/next-start:48:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-next-example-app@ start: `next start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-next-example-app@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2017-06-25T20_12_16_275Z-debug.log
```

### Environment

Run these commands in the project folder and fill in their results:

1. `create-next-app --version`: **0.5.1**
2. `node --version`: **v8.1.1**
3. `npm --version`: **5.0.3**

Then, specify:

1. Operating system: macOS 10.12.5 (latest)
2. Browser and version: Latest Chrome/Firefox, but not relevant.

**Comment by pdehaan** [comment]
I can also reproduce this w/ Node 6 and npm 3:

```sh
> create-next-app --version # 0.5.1
> npm version

{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.2',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.98',
  zlib: '1.2.11' }
```

**Comment by pdehaan** [comment]
I should also point out that `npm run dev` seems to work on Node 6/8, it seems like `npm start` is broken (for me) in both envs.

```sh 
$ npm run dev

> create-next-example-app@ dev /Users/pdehaan/dev/tmp/del/next-app-test/bar
> next

> Using "webpack" config function defined in next.config.js.


 DONE  Compiled successfully in 4486ms                                                                                               2:25:06 PM

> Ready on http://localhost:3000
```

**Comment by nilkesede** [comment]
Try run `npm run build` before running `npm start`.

`Could not find a valid build in the '.next' directory! Try building your app with 'next build' bef
ore starting the server.`

**Comment by stephenmathieson** [comment]
@nilkesede is right - you need to build the app before starting.

Reopen if this is still an issue!
